# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/willj/Desktop/University Work/EEE4120F/YODA/YODA_Project/YODA_Project.srcs/sources_1/ip/FP_Multiplier/FP_Multiplier.xci
# IP: The module: 'FP_Multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/willj/Desktop/University Work/EEE4120F/YODA/YODA_Project/YODA_Project.srcs/sources_1/ip/FP_Multiplier/FP_Multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_Multiplier'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/willj/Desktop/University Work/EEE4120F/YODA/YODA_Project/YODA_Project.srcs/sources_1/ip/FP_Multiplier/FP_Multiplier.xci
# IP: The module: 'FP_Multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/willj/Desktop/University Work/EEE4120F/YODA/YODA_Project/YODA_Project.srcs/sources_1/ip/FP_Multiplier/FP_Multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_Multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
